## Polynomial features

In [4]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

seed = 42
np.random.seed(seed)

Generate data

In [22]:
x = np.arange(6).reshape((3,2))
x

array([[0, 1],
       [2, 3],
       [4, 5]])

Features included: $(x_1^2, x_2^2, x_1x_2)$

In [28]:
poly = PolynomialFeatures(degree=2, include_bias=False)
poly.fit_transform(x)

array([[ 0.,  1.,  0.,  0.,  1.],
       [ 2.,  3.,  4.,  6.,  9.],
       [ 4.,  5., 16., 20., 25.]])

Only interaction terms $x_1x_2$

In [29]:
poly = PolynomialFeatures(degree=2, include_bias=False, interaction_only=True)
poly.fit_transform(x)

array([[ 0.,  1.,  0.],
       [ 2.,  3.,  6.],
       [ 4.,  5., 20.]])

Order parameter

In [30]:
# order parameter
# Order of output array in the dense case. 
# ‘F’ order is faster to compute, but may slow down subsequent estimators.

poly = PolynomialFeatures(degree=2, 
                          include_bias=False, 
                          interaction_only=True, 
                          order="F")
poly.fit_transform(x)

array([[ 0.,  1.,  0.],
       [ 2.,  3.,  6.],
       [ 4.,  5., 20.]])